from django import forms

currencies = [
    ("AED",	"United Arab Emirates Dirham"),
    ("AFN",	"Afghan Afghani"),
    ("ALL",	"Albanian Lek"),
    ("AMD",	"Armenian Dram"),
    ("ANG",	"Netherlands Antillean Guilder"),
    ("AOA",	"Angolan Kwanza"),
    ("ARS",	"Argentine Peso"),
    ("AUD",	"Australian Dollar"),
    ("AWG",	"Aruban Florin"),
    ("AZN",	"Azerbaijani Manat"),
    ("BAM",	"Bosnia-Herzegovina Convertible Mark"),
    ("BBD",	"Barbadian Dollar"),
    ("BDT",	"Bangladeshi Taka"),
    ("BGN",	"Bulgarian Lev"),
    ("BHD",	"Bahraini Dinar"),
    ("BIF",	"Burundian Franc"),
    ("BMD",	"Bermudan Dollar"),
    ("BND",	"Brunei Dollar"),
    ("BOB",	"Bolivian Boliviano"),
    ("BRL",	"Brazilian Real"),
    ("BSD",	"Bahamian Dollar"),
    ("BTN",	"Bhutanese Ngultrum"),
    ("BWP",	"Botswanan Pula"),
    ("BZD",	"Belize Dollar"),
    ("CAD",	"Canadian Dollar"),
    ("CDF",	"Congolese Franc"),
    ("CHF",	"Swiss Franc"),
    ("CLF",	"Chilean Unit of Account UF"),
    ("CLP",	"Chilean Peso"),
    ("CNH",	"Chinese Yuan Offshore"),
    ("CNY",	"Chinese Yuan"),
    ("COP",	"Colombian Peso"),
    ("CUP",	"Cuban Peso"),
    ("CVE",	"Cape Verdean Escudo"),
    ("CZK",	"Czech Republic Koruna"),
    ("DJF",	"Djiboutian Franc"),
    ("DKK",	"Danish Krone"),
    ("DOP",	"Dominican Peso"),
    ("DZD",	"Algerian Dinar"),
    ("EGP",	"Egyptian Pound"),
    ("ERN",	"Eritrean Nakfa"),
    ("ETB",	"Ethiopian Birr"),
    ("EUR",	"Euro"),
    ("FJD",	"Fijian Dollar"),
    ("FKP",	"Falkland Islands Pound"),
    ("GBP",	"British Pound Sterling"),
    ("GEL",	"Georgian Lari"),
    ("GHS",	"Ghanaian Cedi"),
    ("GIP",	"Gibraltar Pound"),
    ("GMD",	"Gambian Dalasi"),
    ("GNF",	"Guinean Franc"),
    ("GTQ",	"Guatemalan Quetzal"),
    ("GYD",	"Guyanaese Dollar"),
    ("HKD",	"Hong Kong Dollar"),
    ("HNL",	"Honduran Lempira"),
    ("HRK",	"Croatian Kuna"),
    ("HTG",	"Haitian Gourde"),
    ("HUF",	"Hungarian Forint"),
    ("ICP",	"Internet Computer"),
    ("IDR",	"Indonesian Rupiah"),
    ("ILS",	"Israeli New Sheqel"),
    ("INR",	"Indian Rupee"),
    ("IQD",	"Iraqi Dinar"),
    ("IRR",	"Iranian Rial"),
    ("ISK",	"Icelandic Krona"),
    ("JEP",	"Jersey Pound"),
    ("JMD",	"Jamaican Dollar"),
    ("JOD",	"Jordanian Dinar"),
    ("JPY",	"Japanese Yen"),
    ("KES",	"Kenyan Shilling"),
    ("KGS",	"Kyrgystani Som"),
    ("KHR",	"Cambodian Riel"),
    ("KMF",	"Comorian Franc"),
    ("KPW",	"North Korean Won"),
    ("KRW",	"South Korean Won"),
    ("KWD",	"Kuwaiti Dinar"),
    ("KYD",	"Cayman Islands Dollar"),
    ("KZT",	"Kazakhstani Tenge"),
    ("LAK",	"Laotian Kip"),
    ("LBP",	"Lebanese Pound"),
    ("LKR",	"Sri Lankan Rupee"),
    ("LRD",	"Liberian Dollar"),
    ("LSL",	"Lesotho Loti"),
    ("LYD",	"Libyan Dinar"),
    ("MAD",	"Moroccan Dirham"),
    ("MDL",	"Moldovan Leu"),
    ("MGA",	"Malagasy Ariary"),
    ("MKD",	"Macedonian Denar"),
    ("MMK",	"Myanma Kyat"),
    ("MNT",	"Mongolian Tugrik"),
    ("MOP",	"Macanese Pataca"),
    ("MRO",	"Mauritanian Ouguiya (pre-2018)"),
    ("MRU",	"Mauritanian Ouguiya"),
    ("MUR",	"Mauritian Rupee"),
    ("MVR",	"Maldivian Rufiyaa"),
    ("MWK",	"Malawian Kwacha"),
    ("MXN",	"Mexican Peso"),
    ("MYR",	"Malaysian Ringgit"),
    ("MZN",	"Mozambican Metical"),
    ("NAD",	"Namibian Dollar"),
    ("NGN",	"Nigerian Naira"),
    ("NOK",	"Norwegian Krone"),
    ("NPR",	"Nepalese Rupee"),
    ("NZD",	"New Zealand Dollar"),
    ("OMR",	"Omani Rial"),
    ("PAB",	"Panamanian Balboa"),
    ("PEN",	"Peruvian Nuevo Sol"),
    ("PGK",	"Papua New Guinean Kina"),
    ("PHP",	"Philippine Peso"),
    ("PKR",	"Pakistani Rupee"),
    ("PLN",	"Polish Zloty"),
    ("PYG",	"Paraguayan Guarani"),
    ("QAR",	"Qatari Rial"),
    ("RON",	"Romanian Leu"),
    ("RSD",	"Serbian Dinar"),
    ("RUB",	"Russian Ruble"),
    ("RUR",	"Old Russian Ruble"),
    ("RWF",	"Rwandan Franc"),
    ("SAR",	"Saudi Riyal"),
    ("SBD","	Solomon Islands Dollar"),
    ("SCR",	"Seychellois Rupee"),
    ("SDG",	"Sudanese Pound"),
    ("SDR",	"Special Drawing Rights"),
    ("SEK",	"Swedish Krona"),
    ("SGD",	"Singapore Dollar"),
    ("SHP",	"Saint Helena Pound"),
    ("SLL",	"Sierra Leonean Leone"),
    ("SOS",	"Somali Shilling"),
    ("SRD",	"Surinamese Dollar"),
    ("SYP",	"Syrian Pound"),
    ("SZL",	"Swazi Lilangeni"),
    ("THB",	"Thai Baht"),
    ("TJS",	"Tajikistani Somoni"),
    ("TMT",	"Turkmenistani Manat"),
    ("TND",	"Tunisian Dinar"),
    ("TOP",	"Tongan Pa'anga"),
    ("TRY",	"Turkish Lira"),
    ("TTD",	"Trinidad and Tobago Dollar"),
    ("TWD",	"New Taiwan Dollar"),
    ("TZS",	"Tanzanian Shilling"),
    ("UAH",	"Ukrainian Hryvnia"),
    ("UGX",	"Ugandan Shilling"),
    ("USD",	"United States Dollar"),
    ("UYU",	"Uruguayan Peso"),
    ("UZS",	"Uzbekistan Som"),
    ("VND",	"Vietnamese Dong"),
    ("VUV",	"Vanuatu Vatu"),
    ("WST",	"Samoan Tala"),
    ("XAF",	"CFA Franc BEAC"),
    ("XCD",	"East Caribbean Dollar"),
    ("XDR",	"Special Drawing Rights"),
    ("XOF",	"CFA Franc BCEAO"),
    ("XPF",	"CFP Franc"),
    ("YER",	"Yemeni Rial"),
    ("ZAR",	"South African Rand"),
    ("ZMW",	"Zambian Kwacha"),
    ("ZWL",	"Zimbabwean Dollar"),
]

class ContactForm(forms.Form):
    sender_email = forms.EmailField(required=False)
    sender_subject = forms.CharField(required=False)
    sender_message = forms.CharField(widget=forms.Textarea, required=False)
    
class SymbolValues(forms.Form):
    symbol_values = [
        ("VZ", "Verizon Communications"), ("KO", "The Coca-Cola Company"), ("NFLX", "Netflix"), ("ADBE", "Adobe Inc."), ("CSCO", "Cisco Systems"), ("XOM", "Exxon Mobil Corporation"), ("CMG", "Chipotle Mexican Grill"), ("SBUX", "Starbucks Corporation"), ("PFE", "Pfizer Inc."), ("CRM", "Salesforce"), 
        ("WMT", "Walmart Inc."), ("HD", "The Home Depot"), ("GE", "General Electric Company"), ("PEP", "PepsiCo, Inc."), ("T", "AT&T Inc."), ("FDX", "FedEx Corporation"), ("INTC", "Intel Corporation"), ("MU", "Micron Technology, Inc."), ("GM", "General Motors Company"), ("COST", "Costco Wholesale Corporation"), 
        ("TWTR", "Twitter, Inc."), ("MS", "Morgan Stanley"), ("CAT", "Caterpillar Inc."), ("MMM", "3M Company"), ("UPS", "United Parcel Service"), ("BKNG", "Booking Holdings Inc."), ("MCD", "McDonald's Corporation"), ("ABT", "Abbott Laboratories"), ("BMY", "Bristol Myers Squibb"), ("WBA", "Walgreens Boots Alliance, Inc."),
        ("IBM", "International Business Machines Corporation"), ("NVDA", "NVIDIA Corporation"), ("AAPL", "Apple Inc."), ("MSFT", "Microsoft Corporation"), ("AMZN", "Amazon.com, Inc."), ("GOOGL", "Alphabet Inc."), ("FB", "Meta Platforms, Inc."), ("TSLA", "Tesla, Inc."), ("JPM", "JPMorgan Chase & Co."), ("JNJ", "Johnson & Johnson"), 
        ("V", "Visa Inc."), ("PG", "Procter & Gamble Company"), ("HD", "The Home Depot, Inc."), ("UNH", "UnitedHealth Group Incorporated"), ("MA", "Mastercard Incorporated"), ("BAC", "Bank of America Corp."), ("DIS", "The Walt Disney Company"), ("PYPL", "PayPal Holdings, Inc."), ("INTC", "Intel Corporation"), ("CMCSA", "Comcast Corporation"), 
        ("VZ", "Verizon Communications Inc."), ("KO", "The Coca-Cola Company"), ("NFLX", "Netflix, Inc."), ("ADBE", "Adobe Inc."), ("CSCO", "Cisco Systems, Inc."), ("XOM", "Exxon Mobil Corporation"), ("CMG", "Chipotle Mexican Grill, Inc."), ("SBUX", "Starbucks Corporation"), ("PFE", "Pfizer Inc."), ("CRM", "salesforce.com, inc."), 
        ("WMT", "Walmart Inc."), ("HD", "The Home Depot, Inc."), ("GE", "General Electric Company"), ("PEP", "PepsiCo, Inc."), ("T", "AT&T Inc."), ("FDX", "FedEx Corporation"), ("INTC", "Intel Corporation"), ("MU", "Micron Technology, Inc."), ("GM", "General Motors Company"), ("COST", "Costco Wholesale Corporation"), 
        ("TWTR", "Twitter, Inc."), ("MS", "Morgan Stanley"), ("CAT", "Caterpillar Inc."), ("MMM", "3M Company"), ("UPS", "United Parcel Service, Inc."), ("BKNG", "Booking Holdings Inc."), ("MCD", "McDonald's Corporation"), ("ABT", "Abbott Laboratories"), ("BMY", "Bristol Myers Squibb Company"), ("WBA", "Walgreens Boots Alliance, Inc."),
        ("NKE", "NIKE, Inc."), ("MO", "Altria Group, Inc."), ("BLK", "BlackRock, Inc."), ("IBM", "International Business Machines Corporation"), ("NVDA", "NVIDIA Corporation"), ("AAPL", "Apple Inc."), ("MSFT", "Microsoft Corporation"), ("AMZN", "Amazon.com, Inc."), ("GOOGL", "Alphabet Inc."), ("FB", "Meta Platforms, Inc."), 
        ("TSLA", "Tesla, Inc."), ("JPM", "JPMorgan Chase & Co."), ("JNJ", "Johnson & Johnson"), ("V", "Visa Inc."), ("PG", "Procter & Gamble Company"), ("HD", "The Home Depot, Inc."), ("UNH", "UnitedHealth Group Incorporated"), ("MA", "Mastercard Incorporated"), ("BAC", "Bank of America Corp."), ("DIS", "The Walt Disney Company"), 
        ("PYPL", "PayPal Holdings, Inc."), ("INTC", "Intel Corporation"), ("CMCSA", "Comcast Corporation"), ("VZ", "Verizon Communications Inc."), ("KO", "The Coca-Cola Company"), ("NFLX", "Netflix, Inc."), ("ADBE", "Adobe Inc."), ("CSCO", "Cisco Systems, Inc."), ("XOM", "Exxon Mobil Corporation"), ("CMG", "Chipotle Mexican Grill, Inc."), 
        ("SBUX", "Starbucks Corporation"), ("PFE", "Pfizer Inc."), ("CRM", "salesforce.com, inc."), ("WMT", "Walmart Inc."), ("HD", "The Home Depot, Inc."), ("GE", "General Electric Company"), ("PEP", "PepsiCo, Inc."), ("T", "AT&T Inc."), ("FDX", "FedEx Corporation"), ("INTC", "Intel Corporation"), ("MU", "Micron Technology, Inc."), 
        ("GM", "General Motors Company"), ("COST", "Costco Wholesale Corporation"), ("TWTR", "Twitter, Inc."), ("MS", "Morgan Stanley"), ("CAT", "Caterpillar Inc."), ("MMM", "3M Company"), ("UPS", "United Parcel Service, Inc."), ("BKNG", "Booking Holdings Inc."), ("MCD", "McDonald's Corporation"), ("ABT", "Abbott Laboratories"), 
        ("BMY", "Bristol Myers Squibb Company"), ("WBA", "Walgreens Boots Alliance, Inc."), ("NKE", "NIKE, Inc."), ("MO", "Altria Group, Inc."), ("BLK", "BlackRock, Inc.")
    ]
    symbol = forms.ChoiceField(choices=symbol_values, required=True)

class StockType(forms.Form):
    stock_type = forms.ChoiceField(choices=[('open', 'Opening value'), ('low', 'Lowest value'),('high', 'Highest value'),('close','Closing value'),('volume','Volume sold')], required=False)

class DataType(forms.Form):
    data_type = forms.ChoiceField(choices=[('INCOME_STATEMENT', 'Income Statement'), ('BALANCE_SHEET', 'Balance Sheet'), ('CASH_FLOW', 'Cash Flow'), ('EARNINGS', 'Earnings')], required=False)

class ToCurrency(forms.Form):
    to_currency = forms.ChoiceField(choices=currencies, required=True)

class FromCurrency(forms.Form):
    from_currency = forms.ChoiceField(choices=currencies, required=True)

class EconForm(forms.Form):
    econ_indicator = forms.ChoiceField(choices=[('REAL_GDP','Real GDP'),('REAL_GDP_PER_CAPITA','Real GDP Per Capita'),('FEDERAL_FUNDS_RATE','Federal Funds Rate'),('CPI','CPI'),('INFLATION','Inflation Rate'),('UNEMPLOYMENT','Unemployment Rate')], required=True)

class CommoditiesForm(forms.Form):
    commodity = forms.ChoiceField(choices=[('WTI','Crude Oil WTI'),('NATURAL_GAS','Natural Gas'),('COPPER','Copper'),('ALUMINUM','Aluminum'),('WHEAT','Wheat'),('CORN','Corn'),('COTTON','Cotton'),('SUGAR','Sugar'),('COFFEE','Coffee')], required=True)