# Generated by Django 5.0.6 on 2024-05-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='estimated_eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earnings',
            name='surprise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earnings',
            name='surprise_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
