# Generated by Django 5.0.6 on 2024-05-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_earnings_estimated_eps_earnings_surprise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='surprise',
            new_name='Surprise',
        ),
    ]
