# Generated by Django 5.0.6 on 2024-05-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_rename_surprise_earnings_surprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='fiscal_date_ending',
            new_name='fiscal_Date_Ending',
        ),
    ]
