# Generated by Django 5.0.6 on 2024-05-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_fiscal_date_ending_earnings_fiscal_date_ending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forex',
            old_name='open_currency_value',
            new_name='exchange_rate',
        ),
    ]
