# Generated by Django 5.0.6 on 2024-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_forex_from_currency_alter_forex_to_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicindicators',
            name='indicator',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
