# Generated by Django 5.0.6 on 2024-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_remove_economicindicators_cpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicindicators',
            name='date_of_indicator',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economicindicators',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
