# Generated by Django 5.0.6 on 2024-05-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_economicindicators_date_of_indicator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EconomicIndicators',
        ),
    ]
