# Generated by Django 5.0.6 on 2024-05-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_delete_economicindicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_indicator', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
