# Generated by Django 5.0.6 on 2024-05-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_economicindicators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodities',
            old_name='date',
            new_name='date_of_commodity',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='aluminum',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='copper',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='corn',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='cotton',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='crude_oil',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='natural_gas',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='commodities',
            name='wheat',
        ),
        migrations.AddField(
            model_name='commodities',
            name='commodity',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='commodities',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
