# Generated by Django 5.0.6 on 2024-05-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_mail_alter_forex_from_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='email_name',
            new_name='subject',
        ),
    ]
